name: Trigger Workflow for Frontend

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger Workflow in Repo B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/obligatorio-devops-agustin/devops/dispatches \
            -d '{
              "event_type": "trigger-frontend",
              "client_payload": {
                "repo": "${{ github.repository }}",
                "branch": "${{ github.ref_name }}",
                "commit": "${{ github.sha }}"
              }
            }'