name: Frontend CI Workflow

on:
  push:
    branches:
      - master
      - release
      - dev

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to analyze"
        required: false
        default: "master"

jobs:
  build-and-analyze:
    name: Build, Test, and Analyze Frontend Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend Application
        run: npm run build

      - name: Run Tests
        run: npm test -- --watchAll=false

      - name: Set up Java 17 for SonarCloud
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=obligatorio-devops-agustin_frontend-app \
            -Dsonar.sources=apps\catalog\src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}
