name: Frontend CI Workflow

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  build-and-analyze:
    name: Build and Analyze Frontend Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend Application
        run: npm run build

      - name: Set up Java 17 for SonarCloud
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=obligatorio-devops-agustin_frontend-application \
            -Dsonar.sources=apps/catalog/src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}

  trigger-cd:
    name: Trigger Frontend CD Workflow
    needs: build-and-analyze
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-analyze.result == 'success' }}
    steps:
      - name: Trigger Frontend CD Workflow
        uses: actions/github-script@v6
        with:
          script: |
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'frontend-cd.yml',
                ref: context.ref,
                inputs: {
                  branch: context.ref.replace('refs/heads/', ''),
                }
              });
